-- AUTO-GENERATED by scripts/seed-posts.mjs — do not edit by hand.
-- Seeds the community feed with realistic member posts.
--
-- Run in the Supabase SQL editor.
--
-- Safe to re-run: each row is skipped when a post with the same title already
-- exists, so this does not depend on a unique constraint and will not duplicate.
--
-- NOTE ON COUNTS: likes and comments are NOT columns on posts — fetchPosts()
-- derives them from the post_likes and comments relations. So these posts will
-- show 0 likes and 0 comments in the live feed regardless of what is seeded
-- here. Seeding realistic counts would need one row per like from a distinct
-- user, since post_likes is keyed by (post_id, user_id).
--
-- user_id is left NULL: the column is nullable, and these posts are not authored
-- by any real account. Attributing them to a member's uuid would make them look
-- like that person's posts to anything that reads user_id.

with seed(pinned, author_name, cat, title, body, created_at) as (
  values
  (true, 'Haply Team', 'Divorce Support', 'Read before posting — what this space is for', 'This is a community for people who are separated or divorced. Vent, ask, celebrate, or just read. No advice-giving unless someone asks for it, and no contact info in public threads. If you are new, saying hello is enough.', now() - interval '0 hours'),
  (false, 'Marcus T.', 'Divorce Support', 'Signed the papers Tuesday and I have not told anyone yet', 'Eleven years. It took four minutes at a desk with a woman who had a photo of her dog on the monitor. I keep opening my phone to tell someone and then closing it. Not sad exactly. Just nothing where something should be. Is that normal or am I about to get hit by a truck emotionally.', now() - interval '3 hours'),
  (false, 'Dana R.', 'Co-Parenting', 'How do you handle the handoff when they are crying?', 'My daughter is 6. Every Sunday at 5 she cries in the car and asks why she has to go. She is fine ten minutes after she gets there — her dad sends a photo, she is laughing. But those ten minutes are wrecking me. Do you say something reassuring or does that make it worse?', now() - interval '6 hours'),
  (false, 'Priya S.', 'Self-Care', 'I cooked a real dinner for one tonight', 'Not standing over the sink. Not cereal. I made the salmon thing I used to make for company, sat at the actual table, and ate it. Small. But I have been living on toast since March so I am counting it.', now() - interval '9 hours'),
  (false, 'Kevin M.', 'Divorce Support', 'The mediator asked what I wanted and I could not answer', 'Genuinely blanked. Twenty two years of knowing what she wanted, what the kids needed, what the mortgage needed. He asked what I want and I sat there. Went home and wrote a list. It was four items long and two of them were about the dog.', now() - interval '14 hours'),
  (false, 'Alicia B.', 'Dating Again', 'First date in 16 years. What do people even do now', 'Coffee on Saturday with someone from a hiking group. Last time I dated, you called a landline. I do not know when texting becomes too much texting, or whether I mention the divorce, or how much. Anyone got a rule of thumb that worked?', now() - interval '19 hours'),
  (false, 'Tom H.', 'Co-Parenting', 'Two years in: the schedule that finally stopped the fighting', 'Posting because I wish someone had told me. We went to 2-2-3 and put everything in a shared calendar that neither of us is allowed to comment in — logistics only, no messages. Every argument we had was actually about tone in the messages, not the schedule. Removing the place to argue removed the arguing.', now() - interval '26 hours'),
  (false, 'Renee W.', 'Divorce Support', 'Does the anger arrive late for anyone else?', 'I was so calm through all of it. Everyone said how well I was handling it. Fourteen months out I am furious, and about specific small things — a comment he made at my brother''s wedding in 2019. It feels like it is happening now. Is this a stage or should I be worried.', now() - interval '31 hours'),
  (false, 'Jordan P.', 'Success Stories', 'Update: the apartment I hated is now the place I like best', 'I posted here in the winter about how much I hated my place. Beige, loud upstairs neighbour, took the first thing available. Painted two walls, got a real bed instead of the mattress on the floor, put my records where I can reach them. Came home Thursday and felt glad to be there. Wanted to report back.', now() - interval '38 hours'),
  (false, 'Nicole F.', 'Self-Care', 'Stopped checking her Instagram. 41 days.', 'It was the last thing I did every night and the first every morning. I would learn something and feel awful for hours. Blocked, not unfollowed — unfollowing left the door open. 41 days and I could not tell you what she did last weekend, which is the point.', now() - interval '44 hours'),
  (false, 'Greg D.', 'Divorce Support', 'Practical: what did nobody warn you about the money side?', 'Six weeks in. Already hit two things I did not expect — the filing fee, and that refinancing in my name alone meant a whole new credit check. What else is coming that people do not mention? Would rather be braced than surprised.', now() - interval '52 hours'),
  (false, 'Bethany L.', 'Co-Parenting', 'His new partner is good with my kids and I feel awful about how much that stings', 'She is genuinely kind to them. My son mentioned she helped him with a science project and I said something clipped that I regretted immediately. I want them to be happy there. I do. Both things are true at once and I do not know what to do with that.', now() - interval '60 hours'),
  (false, 'Sam K.', 'Dating Again', 'When do you tell them how long the marriage was?', 'Twenty three years feels like a number that changes how someone sees you. I have been vague twice and it felt dishonest. Do you lead with it, wait for it to come up, or is it just not the big deal I think it is?', now() - interval '68 hours'),
  (false, 'Carmen O.', 'Self-Care', 'Therapist gave me one sentence that actually helped', '"You are not behind." I had been comparing my nine months to someone else''s three years and treating it as a race I was losing. Writing it here because I would have needed to read it in February.', now() - interval '75 hours'),
  (false, 'Derek A.', 'Divorce Support', 'Told the kids last night. 9 and 13.', 'We did it together, at the kitchen table, kept it short like every guide says. The 13 year old had clearly already worked it out. The 9 year old asked if we were still going to Michigan in July. Then they both went and watched TV and I sat there not knowing what to do with my hands.', now() - interval '84 hours'),
  (false, 'Lauren V.', 'Success Stories', 'One year since I moved out. Some things I know now.', 'The loneliness peaked around month four and then genuinely eased. I made two friends who never knew me as half of a couple, which turned out to matter more than I expected. I still have bad weeks. They are weeks now, not seasons.', now() - interval '96 hours'),
  (false, 'Anthony R.', 'Co-Parenting', 'Anyone else find the empty week harder than the busy one?', 'When I have them I am exhausted and fine. The off week I cannot settle. House is too quiet, I eat standing up, I go to bed at 9. Trying to build something into those weeks rather than just waiting them out. What worked for you?', now() - interval '108 hours'),
  (false, 'Michelle T.', 'Dating Again', 'Second date went well and I panicked about it', 'Nice man, easy conversation, walked me to the car. Got home and felt straight up dread. I think part of me decided that wanting something again is how you get hurt. Working on it. Not cancelling on him.', now() - interval '120 hours'),
  (false, 'Ray B.', 'Divorce Support', 'Sixty two, married thirty one years, starting over', 'I know I am older than most people posting here. Reading these threads has helped more than the two group sessions I went to. If there is anyone else in their sixties doing this, I would like to hear from you. It is a specific kind of quiet.', now() - interval '134 hours'),
  (false, 'Elena G.', 'Self-Care', 'Made a rule: no big decisions after 9pm', 'Every regrettable text, every 2am draft of an email to his lawyer, every online purchase I did not need — all after 9. Now anything that feels urgent at night gets written down and looked at in the morning. About half of it turns out not to matter.', now() - interval '148 hours'),
  (false, 'Chris W.', 'Co-Parenting', 'Do you go to the school events together or split them?', 'First parent-teacher night since the split is next week. She suggested going together for our daughter''s sake. I think I can do it. I am less sure I can do the walking-out-to-separate-cars part afterwards.', now() - interval '162 hours'),
  (false, 'Yolanda M.', 'Success Stories', 'Got the promotion I would have turned down two years ago', 'It needs travel, which never would have worked before. I said yes without running it past anybody, and that part felt stranger than the job itself. Not what I would have chosen, but here we are and it is good.', now() - interval '178 hours'),
  (false, 'Paul S.', 'Divorce Support', 'The grief is not for her, it is for the version of me that was married', 'Took me a long time to work out what I was actually mourning. It is not her — we were miserable and both knew. It is the guy who had a plan. I liked having a plan. Building a new one slowly and it is nothing like the old one.', now() - interval '196 hours'),
  (false, 'Simone A.', 'Dating Again', 'Told him about my kids on the first date and he did not blink', 'I had a whole speech ready because the last one went badly. He asked their names and what they are into. That was it. I had forgotten it could just be a normal fact about a person.', now() - interval '214 hours'),
  (false, 'Nate F.', 'Self-Care', 'Started running because I could not sleep. Kept it because of the mornings.', 'Nothing impressive, three miles, slowly. But I am outside at 6am and it is the only part of the day nobody needs anything from me. Sleeping better too, which was the original point.', now() - interval '238 hours'),
  (false, 'Gina C.', 'Co-Parenting', 'What do you say when they ask if you still love their dad?', 'My son asked in the car, which is where all the real questions happen apparently. I said something about loving him for a long time and that changing. He seemed to accept it. I have no idea if it was the right answer.', now() - interval '262 hours'),
  (false, 'Doug H.', 'Divorce Support', 'Nine months out. Ask me anything, I have made most of the mistakes.', 'Sent the long email. Went to the wedding I should have skipped. Told my kids more than they needed. Dated someone three weeks after moving out. All survivable, none recommended. Happy to answer anything if it saves someone a step.', now() - interval '290 hours'),
  (false, 'Farah N.', 'Success Stories', 'My daughter told me the house feels calmer now', 'She is 15 and not given to reassuring anybody. She said it offhand, doing homework. I had spent two years assuming I had broken something for her. I went into the other room and cried, then made dinner.', now() - interval '320 hours')
)
insert into public.posts (user_id, author_name, cat, title, body, pinned, created_at)
select
  null,
  s.author_name, s.cat, s.title, s.body, s.pinned, s.created_at
from seed s
where not exists (select 1 from public.posts p where p.title = s.title);

-- Verify:
--   select cat, count(*) from public.posts group by cat order by 2 desc;
--   select author_name, title, created_at from public.posts order by created_at desc limit 10;
