-- AUTO-GENERATED by scripts/seed-posts.mjs — do not edit by hand.
-- Seeds the community feed with the team's opening conversation prompts.
--
-- Run in the Supabase SQL editor.
--
-- Safe to re-run: each row is skipped when a post with the same title already
-- exists, so this does not depend on a unique constraint and will not duplicate.
--
-- OPERATOR CONTENT ONLY. Every row is written by the Haply team and posts under
-- the team's name. This file previously seeded 27 posts under invented member
-- names carrying invented personal testimony; they were deleted from the live
-- table and must not come back. See scripts/seed-posts.mjs for the reasoning.
--
-- Engagement counts are not seeded and not seedable: likes and comments are not
-- columns on posts, fetchPosts() derives them from the post_likes and comments
-- relations, and post_likes is keyed by (post_id, user_id) — so a realistic
-- count would require inventing one user row per like.
--
-- user_id is left NULL: the column is nullable, and these posts are not authored
-- by any real member account. Attributing them to a member's uuid would make them
-- look like that person's posts to anything that reads user_id.

with seed(pinned, author_name, cat, title, body, created_at) as (
  values
  (true, 'Haply Team', 'Divorce Support', 'Read before posting — what this space is for', 'This is a community for people who are separated or divorced. Vent, ask, celebrate, or just read. No advice-giving unless someone asks for it, and no contact info in public threads. If you are new, saying hello is enough.', now() - interval '0 hours'),
  (true, 'Haply Team', 'Divorce Support', 'Welcome to Haply — introduce yourself', 'Tell the community a little about where you are in your journey. New here? Start with hello — someone will be glad you did.', now() - interval '0 hours'),
  (true, 'Haply Team', 'Co-Parenting', 'Co-parents: what is working for you?', 'Schedules, hand-offs, holidays — share what has made two-home parenting smoother for your family.', now() - interval '0 hours'),
  (true, 'Haply Team', 'Dating Again', 'What does "ready to date" feel like?', 'There''s no deadline. Share how you knew it was time — or ask the community how they knew.', now() - interval '0 hours'),
  (true, 'Haply Team', 'Self-Care', 'One small win this week', 'Big or small, share a win. This thread is for cheering each other on.', now() - interval '0 hours')
)
insert into public.posts (user_id, author_name, cat, title, body, pinned, created_at)
select
  null,
  s.author_name, s.cat, s.title, s.body, s.pinned, s.created_at
from seed s
where not exists (select 1 from public.posts p where p.title = s.title);

-- Verify — every seeded row should read 'Haply Team':
--   select author_name, count(*) from public.posts where user_id is null group by 1;
--   select author_name, title, created_at from public.posts order by created_at desc limit 10;
