// Community starter content. Emits two artifacts from one source so they can't drift:
//   src/haply/communityPosts.ts  — the client-side fallback / pre-fetch state
//   supabase/seed/posts.sql      — rows for the live posts table
// Run: node scripts/seed-posts.mjs
//
// WHAT THIS DELIBERATELY NO LONGER CONTAINS
//
// This file used to seed 27 posts under invented member names — "Marcus T.",
// "Dana R." — each carrying invented personal testimony about signing divorce
// papers, crying children at custody handoffs, and therapy. They also carried
// invented like and comment counts in the hundreds.
//
// It is the same mistake data.ts already rejects for profiles, and it is worse
// here. A fake profile is a padded number; a fake confession about someone's
// 6-year-old is fabricated intimate testimony, published under a name, on a
// product whose entire premise is that it verifies members are who they claim.
// The first journalist or member who diffs the seed file against the member
// count has the story, and in this category trust is the product — it is the
// only thing Haply sells that SilverSingles cannot buy.
//
// So: operator content only. Every post below is genuinely written by the Haply
// team, posts under the team's own name, and claims nothing about a member who
// does not exist. Empty categories stay empty until real people fill them. If
// you are tempted to add "just a few" member posts to make the feed look alive,
// read the note in src/haply/data.ts first — an empty room is recoverable, a
// room full of invented grief is not.
//
// Engagement counts are hardcoded 0. They are not columns on posts; fetchPosts()
// derives them from post_likes and comments. Any nonzero number written here is
// a fabrication that the live feed will contradict anyway.
import { writeFileSync, mkdirSync } from 'node:fs';

const POSTS = [
  { hoursAgo: 0, pinned: true, name: 'Haply Team', cat: 'Divorce Support',
    title: 'Read before posting — what this space is for',
    body: 'This is a community for people who are separated or divorced. Vent, ask, celebrate, or just read. No advice-giving unless someone asks for it, and no contact info in public threads. If you are new, saying hello is enough.' },

  { hoursAgo: 0, pinned: true, name: 'Haply Team', cat: 'Divorce Support',
    title: 'Welcome to Haply — introduce yourself',
    body: 'Tell the community a little about where you are in your journey. New here? Start with hello — someone will be glad you did.' },

  { hoursAgo: 0, pinned: true, name: 'Haply Team', cat: 'Co-Parenting',
    title: 'Co-parents: what is working for you?',
    body: 'Schedules, hand-offs, holidays — share what has made two-home parenting smoother for your family.' },

  { hoursAgo: 0, pinned: true, name: 'Haply Team', cat: 'Dating Again',
    title: 'What does "ready to date" feel like?',
    body: "There's no deadline. Share how you knew it was time — or ask the community how they knew." },

  { hoursAgo: 0, pinned: true, name: 'Haply Team', cat: 'Self-Care',
    title: 'One small win this week',
    body: 'Big or small, share a win. This thread is for cheering each other on.' },
];

const label = (h) => {
  if (h === 0) return 'Pinned';
  if (h < 1) return 'Just now';
  if (h < 24) return `${h} hours ago`;
  const d = Math.round(h / 24);
  return d === 1 ? '1 day ago' : `${d} days ago`;
};

// --- TypeScript fallback ---
const ts = `// AUTO-GENERATED by scripts/seed-posts.mjs — do not edit by hand.
// Client-side fallback and pre-fetch state, shown only if the live fetch fails.
// The live feed is served from the Supabase \`posts\` table; seed it with
// supabase/seed/posts.sql.
//
// Operator content only — these are conversation prompts written by the Haply
// team under the team's own name. No invented members, no invented engagement
// counts. See the header of scripts/seed-posts.mjs for why.
import type { Post } from './data';

export const COMMUNITY_POSTS: Post[] = [
${POSTS.map((p, i) => `  ${JSON.stringify({ id: i + 1, name: p.name, cat: p.cat, time: label(p.hoursAgo), title: p.title, body: p.body, likes: 0, comments: 0 })},`).join('\n')}
];
`;
writeFileSync('src/haply/communityPosts.ts', ts);

// --- SQL seed ---
const esc = (s) => s.replace(/'/g, "''");
const rows = POSTS.map(
  (p) =>
    `  (${p.pinned ? 'true' : 'false'}, '${esc(p.name)}', '${esc(p.cat)}', '${esc(p.title)}', '${esc(p.body)}', now() - interval '${p.hoursAgo} hours')`
).join(',\n');

const sql = `-- AUTO-GENERATED by scripts/seed-posts.mjs — do not edit by hand.
-- Seeds the community feed with the team's opening conversation prompts.
--
-- Run in the Supabase SQL editor.
--
-- Safe to re-run: each row is skipped when a post with the same title already
-- exists, so this does not depend on a unique constraint and will not duplicate.
--
-- OPERATOR CONTENT ONLY. Every row is written by the Haply team and posts under
-- the team's name. This file previously seeded 27 posts under invented member
-- names carrying invented personal testimony; they were deleted from the live
-- table and must not come back. See scripts/seed-posts.mjs for the reasoning.
--
-- Engagement counts are not seeded and not seedable: likes and comments are not
-- columns on posts, fetchPosts() derives them from the post_likes and comments
-- relations, and post_likes is keyed by (post_id, user_id) — so a realistic
-- count would require inventing one user row per like.
--
-- user_id is left NULL: the column is nullable, and these posts are not authored
-- by any real member account. Attributing them to a member's uuid would make them
-- look like that person's posts to anything that reads user_id.

with seed(pinned, author_name, cat, title, body, created_at) as (
  values
${rows}
)
insert into public.posts (user_id, author_name, cat, title, body, pinned, created_at)
select
  null,
  s.author_name, s.cat, s.title, s.body, s.pinned, s.created_at
from seed s
where not exists (select 1 from public.posts p where p.title = s.title);

-- Verify — every seeded row should read 'Haply Team':
--   select author_name, count(*) from public.posts where user_id is null group by 1;
--   select author_name, title, created_at from public.posts order by created_at desc limit 10;
`;
mkdirSync('supabase/seed', { recursive: true });
writeFileSync('supabase/seed/posts.sql', sql);

const byCat = {};
for (const p of POSTS) byCat[p.cat] = (byCat[p.cat] || 0) + 1;
console.error(`wrote ${POSTS.length} operator posts (no member content)`);
console.error('by category:', JSON.stringify(byCat));
