// AUTO-GENERATED by scripts/seed-posts.mjs — do not edit by hand.
// Client-side fallback and pre-fetch state, shown only if the live fetch fails.
// The live feed is served from the Supabase `posts` table; seed it with
// supabase/seed/posts.sql.
//
// Operator content only — these are conversation prompts written by the Haply
// team under the team's own name. No invented members, no invented engagement
// counts. See the header of scripts/seed-posts.mjs for why.
import type { Post } from './data';

export const COMMUNITY_POSTS: Post[] = [
  {"id":1,"name":"Haply Team","cat":"Divorce Support","time":"Pinned","title":"Read before posting — what this space is for","body":"This is a community for people who are separated or divorced. Vent, ask, celebrate, or just read. No advice-giving unless someone asks for it, and no contact info in public threads. If you are new, saying hello is enough.","likes":0,"comments":0},
  {"id":2,"name":"Haply Team","cat":"Divorce Support","time":"Pinned","title":"Welcome to Haply — introduce yourself","body":"Tell the community a little about where you are in your journey. New here? Start with hello — someone will be glad you did.","likes":0,"comments":0},
  {"id":3,"name":"Haply Team","cat":"Co-Parenting","time":"Pinned","title":"Co-parents: what is working for you?","body":"Schedules, hand-offs, holidays — share what has made two-home parenting smoother for your family.","likes":0,"comments":0},
  {"id":4,"name":"Haply Team","cat":"Dating Again","time":"Pinned","title":"What does \"ready to date\" feel like?","body":"There's no deadline. Share how you knew it was time — or ask the community how they knew.","likes":0,"comments":0},
  {"id":5,"name":"Haply Team","cat":"Self-Care","time":"Pinned","title":"One small win this week","body":"Big or small, share a win. This thread is for cheering each other on.","likes":0,"comments":0},
];
